name: zx_tgseach

on:
    workflow_dispatch:
    push:
      branches:
        - master
      paths:
        - "zx_tgseach/**"
        - ".github/workflows/zx_tgseach.yml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master

      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.S_DOCKER_USERNAME }}/zx_tgseach
          tags: |
            type=raw,value=latest

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v3
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.S_DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Get
        run: |
          mkdir -p zx_tgseach/linux/arm64
          mkdir -p zx_tgseach/linux/arm/v7
          mkdir -p zx_tgseach/linux/amd64
          ls -al zx_tgseach
          curl -L -o ./zx_tgseach/linux/arm/v7/tgsearch 'https://gitlab.com/tvbox2/telegram-channel-video-downloader/-/raw/main/tgsou-armV7?ref_type=heads&inline=false'
          curl -L -o ./zx_tgseach/linux/arm64/tgsearch 'https://gitlab.com/tvbox2/telegram-channel-video-downloader/-/raw/main/tgsou-arm64?ref_type=heads&inline=false'
          curl -L -o ./zx_tgseach/linux/amd64/tgsearch 'https://gitlab.com/tvbox2/telegram-channel-video-downloader/-/raw/main/tgsou-linux?ref_type=heads&inline=false'
          ls -al zx_tgseach/linux

      - 
        name: Build
        uses: docker/build-push-action@v6
        with:
          context: ./zx_tgseach
          file: zx_tgseach/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
